// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";

// Load Inter font and define a CSS variable
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"], // adjust as needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="font-sans bg-white text-black min-h-screen">
        {children}
      </body>
    </html>
  );
}
